import 'package:flutter/material.dart';

const primaryColor = Color(0xFF000000);
const secondaryColor = Color(0xFFffffff);
const appColor = Color(0xFF005CFF);
const primaryTextColor = Color(0xFF1E1E1E);
const inactiveColor = Color(0xFFE4E4EC);
const lightTextColor = Color(0xFF7F8184);
const iconColor = Color(0xFF1C1B1F);
const secondaryTextColor = Color(0xFFC9519A);
const darkTextColor = Color(0xFF262B27);
const borderColor = Color(0xFF909090);
const bgColor = Color(0xFFD470A9);
const appSecColor = Color(0xFFB73587);
const lightGreyColor = Color(0xFF818086);
const borderPinkColor = Color(0xFFF8F7FD);
const ratingColor= Color(0xffFEB53E);
const ratingTextColor = Color(0xffBBBBBB);
const backgroundColor = Color(0xffE4E4EC);
const boxColor= Color(0xffB4B4D3);
const dividerColor = Color(0xffE4E4EC);
const lineColor = Color(0xff05122B);
const boxBackgroundColor = Color(0xffEDEDED);
